export const ComponentMeta = {
  name: 'Card',
  slug: 'card',
  version: '1.0.0',
  description: 'Content card with style variants (light, dark, high-contrast), layout directions, image, and action buttons.',
  props: [
    { name: 'title',            type: 'string',                                         required: true,  default: undefined,    description: 'Card heading text' },
    { name: 'url',              type: 'string',                                         required: false, default: undefined,    description: 'Makes the title a link when provided' },
    { name: 'style',            type: "'light' | 'high-contrast' | 'dark'",             required: false, default: 'light',      description: 'Visual style variant' },
    { name: 'direction',        type: "'vertical' | 'horizontal' | 'horizontal-reverse'", required: false, default: 'vertical', description: 'Layout direction' },
    { name: 'image',            type: '{ src: string; alt: string }',                   required: false, default: undefined,    description: 'Image displayed in the card header' },
    { name: 'buttonPrimary',    type: 'string',                                         required: false, default: undefined,    description: 'Primary action button label' },
    { name: 'buttonPrimaryUrl', type: 'string',                                         required: false, default: undefined,    description: 'Primary button href' },
    { name: 'buttonSecondary',  type: 'string',                                         required: false, default: undefined,    description: 'Secondary action button label' },
    { name: 'buttonSecondaryUrl', type: 'string',                                       required: false, default: undefined,    description: 'Secondary button href' },
    { name: 'children',         type: 'ReactNode',                                      required: false, default: undefined,    description: 'Body slot — main card content' },
    { name: 'addClassName',     type: 'string',                                         required: false, default: undefined,    description: 'Extra classes appended to the root element' },
  ],
  cssVars: [
    { name: '--pu-card-bg',                       default: '#ffffff',     description: 'Card background color' },
    { name: '--pu-card-color',                    default: '#111827',     description: 'Card text color' },
    { name: '--pu-card-border-radius',            default: '0.5rem',      description: 'Card corner radius' },
    { name: '--pu-card-border',                   default: '1px solid #e5e7eb', description: 'Card border' },
    { name: '--pu-card-padding',                  default: '1.25rem',     description: 'Content area padding' },
    { name: '--pu-card-gap',                      default: '0.75rem',     description: 'Gap between content elements' },
    { name: '--pu-card-image-height',             default: '12rem',       description: 'Image height in vertical layout' },
    { name: '--pu-card-horizontal-image-width',   default: '12rem',       description: 'Image width in horizontal layouts' },
    { name: '--pu-card-title-size',               default: '1.125rem',    description: 'Title font size' },
    { name: '--pu-card-title-weight',             default: '600',         description: 'Title font weight' },
    { name: '--pu-card-title-color',              default: 'inherit',     description: 'Title text color' },
    { name: '--pu-card-body-size',                default: '0.875rem',    description: 'Body text font size' },
    { name: '--pu-card-body-color',               default: '#4b5563',     description: 'Body text color' },
    { name: '--pu-card-btn-radius',               default: '0.375rem',    description: 'Button corner radius' },
    { name: '--pu-card-btn-padding',              default: '0.5rem 1rem', description: 'Button padding' },
    { name: '--pu-card-btn-font-size',            default: '0.875rem',    description: 'Button font size' },
    { name: '--pu-card-btn-primary-bg',           default: '#2563eb',     description: 'Primary button background' },
    { name: '--pu-card-btn-primary-color',        default: '#ffffff',     description: 'Primary button text color' },
    { name: '--pu-card-btn-primary-bg-hover',     default: '#1d4ed8',     description: 'Primary button hover background' },
    { name: '--pu-card-btn-secondary-bg',         default: 'transparent', description: 'Secondary button background' },
    { name: '--pu-card-btn-secondary-color',      default: '#2563eb',     description: 'Secondary button text and border color' },
    { name: '--pu-card-btn-secondary-border',     default: '#2563eb',     description: 'Secondary button border color' },
  ],
}
