export const ComponentMeta = {
  name: 'Button',
  slug: 'button',
  version: '1.0.0',
  description: 'Polymorphic button component with variant, size, icon slots, and ripple interaction. Renders as button or anchor.',
  props: [
    { name: 'children',    type: 'ReactNode',                                                        required: false, default: undefined,  description: 'Button content' },
    { name: 'variant',     type: "'primary' | 'secondary' | 'ghost' | 'outline' | 'danger' | 'link'", required: false, default: 'primary', description: 'Visual variant' },
    { name: 'size',        type: "'sm' | 'md' | 'lg'",                                               required: false, default: 'md',       description: 'Button size' },
    { name: 'as',          type: "'button' | 'a'",                                                   required: false, default: 'button',   description: 'Root HTML element' },
    { name: 'href',        type: 'string',                                                           required: false, default: undefined,  description: 'URL — used when as="a"' },
    { name: 'icon',        type: 'ReactNode',                                                        required: false, default: undefined,  description: 'Left icon slot' },
    { name: 'iconRight',   type: 'ReactNode',                                                        required: false, default: undefined,  description: 'Right icon slot' },
    { name: 'disabled',    type: 'boolean',                                                          required: false, default: false,      description: 'Disables interaction' },
    { name: 'addClassName', type: 'string',                                                          required: false, default: undefined,  description: 'Extra classes appended to the root element' },
  ],
  cssVars: [
    { name: '--pu-button-radius',       default: '0.375rem',  description: 'Border radius' },
    { name: '--pu-button-font-size',    default: '0.875rem',  description: 'Base font size' },
    { name: '--pu-button-font-weight',  default: '600',       description: 'Font weight' },
    { name: '--pu-button-height-sm',    default: '2rem',      description: 'Height at size sm' },
    { name: '--pu-button-height-md',    default: '2.75rem',   description: 'Height at size md' },
    { name: '--pu-button-height-lg',    default: '3.25rem',   description: 'Height at size lg' },
    { name: '--pu-button-padding-sm',   default: '0 0.75rem', description: 'Padding at size sm' },
    { name: '--pu-button-padding-md',   default: '0 1.25rem', description: 'Padding at size md' },
    { name: '--pu-button-padding-lg',   default: '0 1.75rem', description: 'Padding at size lg' },
    { name: '--pu-button-gap',          default: '0.5rem',    description: 'Gap between icon and label' },
    { name: '--pu-button-bg',           default: '#ea580c',   description: 'Background color (primary)' },
    { name: '--pu-button-bg-hover',     default: '#c2410c',   description: 'Hover background color' },
    { name: '--pu-button-color',        default: '#ffffff',   description: 'Text color' },
    { name: '--pu-button-color-hover',  default: '#ffffff',   description: 'Hover text color' },
    { name: '--pu-button-border',       default: 'transparent', description: 'Border color' },
    { name: '--pu-button-border-hover', default: 'transparent', description: 'Hover border color' },
    { name: '--pu-button-transition',   default: 'background 150ms ease, color 150ms ease, border-color 150ms ease, box-shadow 150ms ease', description: 'CSS transition shorthand' },
  ],
}
