export const ComponentMeta = {
  name: 'Badge',
  slug: 'badge',
  version: '1.0.0',
  description: 'Status badge with color variants and optional icon slots. Non-interactive inline element.',
  props: [
    { name: 'label',       type: 'string',                                                                                        required: true,  default: undefined,      description: 'Visible text content of the badge' },
    { name: 'status',      type: "'brand' | 'danger' | 'important' | 'informative' | 'severe' | 'success' | 'warning'",          required: false, default: 'informative',  description: 'Color status variant' },
    { name: 'appearance',  type: "'filled' | 'ghost' | 'outline' | 'tint'",                                                      required: false, default: 'filled',       description: 'Visual fill style' },
    { name: 'iconLeft',    type: 'ReactNode',                                                                                     required: false, default: undefined,      description: 'Optional icon rendered before the label' },
    { name: 'iconRight',   type: 'ReactNode',                                                                                     required: false, default: undefined,      description: 'Optional icon rendered after the label' },
    { name: 'addClassName', type: 'string',                                                                                       required: false, default: undefined,      description: 'Extra classes appended to the root element' },
  ],
  cssVars: [
    { name: '--pu-badge-radius',             default: '100px',       description: 'Border radius (pill shape)' },
    { name: '--pu-badge-border-width',       default: '1.5px',       description: 'Border width' },
    { name: '--pu-badge-padding',            default: '0.125rem 0.625rem', description: 'Padding' },
    { name: '--pu-badge-font-size',          default: '0.75rem',     description: 'Font size' },
    { name: '--pu-badge-font-weight',        default: '700',         description: 'Font weight' },
    { name: '--pu-badge-gap',               default: '0.25rem',     description: 'Gap between icon and label' },
    { name: '--pu-badge-brand-base',        default: '#2563eb',     description: 'Brand status base color' },
    { name: '--pu-badge-brand-tint',        default: '#eff6ff',     description: 'Brand status tint background' },
    { name: '--pu-badge-danger-base',       default: '#dc2626',     description: 'Danger status base color' },
    { name: '--pu-badge-danger-tint',       default: '#fef2f2',     description: 'Danger status tint background' },
    { name: '--pu-badge-important-base',    default: '#7c3aed',     description: 'Important status base color' },
    { name: '--pu-badge-important-tint',    default: '#f5f3ff',     description: 'Important status tint background' },
    { name: '--pu-badge-informative-base',  default: '#0891b2',     description: 'Informative status base color' },
    { name: '--pu-badge-informative-tint',  default: '#ecfeff',     description: 'Informative status tint background' },
    { name: '--pu-badge-severe-base',       default: '#ea580c',     description: 'Severe status base color' },
    { name: '--pu-badge-severe-tint',       default: '#fff7ed',     description: 'Severe status tint background' },
    { name: '--pu-badge-success-base',      default: '#16a34a',     description: 'Success status base color' },
    { name: '--pu-badge-success-tint',      default: '#f0fdf4',     description: 'Success status tint background' },
    { name: '--pu-badge-warning-base',      default: '#ca8a04',     description: 'Warning status base color' },
    { name: '--pu-badge-warning-tint',      default: '#fefce8',     description: 'Warning status tint background' },
  ],
}
